trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  buildConfiguration: 'Release'

stages:
- stage: test

  jobs:
  - job: sonar
    displayName: Analyse code with SonarQube

    steps:
    - task: SonarCloudPrepare@1
      displayName: 'Prepare SonarCloud analysis'
      inputs:
        SonarCloud: 'SonarCloud'
        organization: 'aqualityautomation'
        projectKey: 'aquality-automation_aquality-tracking-integrations-dotnet'
        projectName: 'aquality-tracking-integrations-dotnet'
        projectVersion: '$(Build.BuildNumber)'
        extraProperties: |
          sonar.coverage.exclusions=**/**
    
    - task: DotNetCoreCLI@2
      displayName: 'Build solution'
      inputs:
        command: 'build'
        projects: AqualityTracking.Integrations/AqualityTracking.Integrations.sln
        arguments: -c $(buildConfiguration)

    - task: SonarCloudAnalyze@1
      displayName: 'Run SonarCloud code analysis'
      continueOnError: true

    - task: SonarCloudPublish@1
      displayName: 'Publish SonarCloud quality gate results'
- stage: deploy
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))

  jobs:
  - job: release
    displayName: 'Publish NuGet package'

  steps:
  - task: gitversion/setup@0
    displayName: 'Install GitTools'
    inputs:
    versionSpec: '5.x'
  - task: gitversion/execute@0
    inputs:
    useConfigFile: true
    configFilePath: 'GitVersion.yml'

  - script: dotnet pack Aquality.Integrations.Core/src/AqualityTracking.ReqnrollPlugin.csproj -c $(buildConfiguration) -p:Version=$(GitVersion.NuGetVersion) -o $(Build.ArtifactStagingDirectory)
    displayName: 'Pack to NuGet package'

  - task: NuGetCommand@2
    displayName: 'Push NuGet package'
    inputs:
    command: 'push'
    packagesToPush: '$(Build.ArtifactStagingDirectory)/**/AqualityTracking.ReqnrollPlugin*.nupkg;!$(Build.ArtifactStagingDirectory)/**/Aquality.Selenium*.symbols.nupkg'
    nuGetFeedType: 'external'
    publishFeedCredentials: 'NuGet'