<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <Version>1.0.0</Version>
    <GeneratePackageOnBuild>false</GeneratePackageOnBuild>
    <PackageRequireLicenseAcceptance>true</PackageRequireLicenseAcceptance>
    <Authors>aquality automation committers</Authors>
    <Company>aquality automation</Company>
    <Description>Aquality Tracking integration for Reqnroll.NUnit 2.4.1</Description>
    <PackageDescription>Aquality Tracking integration for Reqnroll.NUnit 2.4.1</PackageDescription>
    <RepositoryUrl>https://github.com/aquality-automation/aquality-tracking-integrations-dotnet</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <PackageTags>aquality-tracking</PackageTags>
    <PackageLicenseExpression></PackageLicenseExpression>
    <PackageLicenseFile>LICENSE</PackageLicenseFile>
    <Copyright>Copyright 2020 Aquality Automation</Copyright>
    <IsPackable>true</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="Resources\aqualityTracking.Template.json">
      <Pack>True</Pack>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <None Include="..\..\..\LICENSE">
      <Pack>True</Pack>
      <PackagePath></PackagePath>
    </None>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Reqnroll.NUnit" Version="2.4.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\AqualityTracking.Integrations.Core\AqualityTracking.Integrations.Core.csproj" />
  </ItemGroup>

</Project>
